name: Terraform Validate and Plan

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

permissions:
  contents: read
  id-token: write

env:
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  AWS_REGION: ${{ secrets.AWS_REGION }}
  ROLE_TO_ASSUME: ${{ secrets.ROLE_TO_ASSUME }}
  GITHUB_REPO_NAME: ${{ github.event.repository.name }}

jobs:
  terraform:
    name: Terraform Validate and Plan
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_wrapper: true
          terraform_version: "1.14.0"

      - name: Configure AWS Credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ env.ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Terraform Init
        run: |
          terraform init -reconfigure \
            -backend-config="bucket=terraform-state-$AWS_ACCOUNT_ID-$AWS_REGION" \
            -backend-config="key=$GITHUB_REPO_NAME/dev/terraform.tfstate" \
            -backend-config="region=$AWS_REGION" \
            -backend-config="encrypt=true" \
            -backend-config="use_lockfile=true"

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        id: plan
        run: |
          # Capture both stdout and stderr, and get exit code

          exit_code=0
          terraform plan -detailed-exitcode -no-color -out tfplan || exit_code=$?

          if [ $exit_code -eq 0 ]; then
            echo "✅ No changes detected"
          elif [ $exit_code -eq 1 ]; then
            echo "❌ Plan failed"
          elif [ $exit_code -eq 2 ]; then
            echo "✅ Changes detected, applying..."
          fi

          echo "Terraform Exit Code: $exit_code"

          echo "exit_code=$exit_code" >> $GITHUB_OUTPUT

          # Capture plan output
          TERRAFORM_PLAN=$(terraform show -no-color tfplan)

          delimiter="$(openssl rand -hex 8)"
          echo "summary<<${delimiter}" >> $GITHUB_OUTPUT
          echo "#### Terraform Plan Output" >> $GITHUB_OUTPUT
          echo "<details><summary>Click to expand</summary>" >> $GITHUB_OUTPUT
          echo "" >> $GITHUB_OUTPUT
          echo '```terraform' >> $GITHUB_OUTPUT
          echo "$TERRAFORM_PLAN" >> $GITHUB_OUTPUT
          echo '```' >> $GITHUB_OUTPUT
          echo "</details>" >> $GITHUB_OUTPUT
          echo "${delimiter}" >> $GITHUB_OUTPUT

          echo "$summary" >> $GITHUB_STEP_SUMMARY

      - name: Final Result Check
        run: |
          EXIT_CODE=${{ steps.plan.outputs.exit_code }}
          if [ $EXIT_CODE -eq 1 ]; then
            echo "❌ Plan failed"
            exit 1
          fi
